(add-to-list 'load-path "~/stack-ide/stack-mode/")
(add-to-list 'load-path "~/.stack/snapshots/x86_64-osx/lts-4.0/7.10.3/share/x86_64-osx-ghc-7.10.3/HaRe-0.8.2.1/elisp/")
;; Install Intero
(require 'haskell-mode)
(require 'haskell-emacs)
(require 'stack-mode)
(require 'intero)
(require 'company-ghc)
(require 'hare)
;; (require 'ghc-mode)
(require 'scion)
(add-hook 'haskell-mode-hook (lambda () (ghc-init) (hare-init)))
(add-hook 'haskell-mode-hook 'flycheck-mode)
(add-hook 'haskell-mode-hook 'stack-mode)
(add-hook 'haskell-mode-hook 'intero-mode)
(intero-global-mode 1)
;; (remove-hook 'haskell-mode-hook 'structured-haskell-mode)
